Default: &defaults
  database: websocktest.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: websocktest_test.sqlite3
  <<: *defaults

Staging:
  database: websocktest_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: websocktest_production.sqlite3
  poolsize: 100
  <<: *defaults
